project_id = "nsdisfhrgxatxaenyrbx"

[functions.instance-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false
